### ISSUE TITLE
It is still trying to use magick even though convert is installed

### ISSUE THREAD

**Issue by Botspot** [l-koehler/FF-converter#3]
![20240102_16h32m28s_grim](https://github.com/l-koehler/FF-converter/assets/54716352/7f412e38-9d0b-42fa-8fff-3e19f34d6e55)
It looks like you have a few more places to use `convert` in place of `magick`.
This screenshot corresponds with the following output on the command-line:
```
Exception in thread Thread-3 (convert):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/pipx/venvs/ffmulticonverter/lib/python3.11/site-packages/ffmulticonverter/progress.py", line 263, in convert
    if conv_func(*params):
       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/pipx/venvs/ffmulticonverter/lib/python3.11/site-packages/ffmulticonverter/progress.py", line 360, in convert_image
    child = subprocess.Popen(
            ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'magick'
```

**Comment by l-koehler** [comment]
should be fixed now.
